sudo: false
language: ruby
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
before_install: gem install bundler -v 1.15.3
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd spec/dummy
  - cp config/database.yml.travis config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate --trace

script:
  - cd ../..
  - rspec

services:
  - postgresql
