sudo: false
language: ruby
rvm:
  - 2.3.1
before_install: gem install bundler -v 1.15.3
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd spec/dummy
  - cp config/database.yml.travis config/database.yml

services:
  - postgresql
